### ISSUE TITLE
K-P-E doesn't work on Kibana OSS 7.0.1 - Missing module "request-promise"?

### ISSUE THREAD

**Issue by duhang** [pjhampton/kibana-prometheus-exporter#76]
**Describe the bug**

I install kibana-prometheus-exporter 7.0.1 on kibana-oss 7.0.1. But I'm gettin error
when trying to start Kibana from a docker container.

**To Reproduce**

Install K-P-E 7.0.1 on Kibana OSS 7.0.1 and start Kibana. It should fail with 
Cannot find module 'request-promise'

{"type":"log","@timestamp":"2019-05-26T05:06:10Z","tags":["fatal","root"],"pid":10,"message":"{ Error: Cannot find module 'request-promise'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:507:25)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.<anonymous> (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/exporter/prometheus.js:2:19)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at loader (/usr/share/kibana/node_modules/babel-register/lib/node.js:144:5)\n    at Object.require.extensions.(anonymous function) [as .js] (/usr/share/kibana/node_modules/babel-register/lib/node.js:154:7)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.<anonymous> (/usr/share/kibana/plugins/kibana-prometheus-exporter/index.js:2:1)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at loader (/usr/share/kibana/node_modules/babel-register/lib/node.js:144:5)\n    at Object.require.extensions.(anonymous function) [as .js] (/usr/share/kibana/node_modules/babel-register/lib/node.js:154:7)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18) code: 'MODULE_NOT_FOUND' }"}

 FATAL  Error: Cannot find module 'request-promise'

**Expected behavior**
Expect K-P-E supports Kibana OSS 7.0.1 or above
(We use K-P-E on Kibana OSS 6.5.4 and it was working fine)

**Screenshots**
N/A

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duhang** [comment]
Sorry, looks like a lot of new dependencies had been added since 6.5.

**Comment by pjhampton** [comment]
@duhang did you mean to close this? It's possible the build was done without an `npm i`.
Let me know.
